### ISSUE TITLE
License problem

### ISSUE THREAD

**Issue by findlabnet** [backdrop-contrib/elevation#1]
Seems like license violation.
https://pixelarity.com/license (part 4. Prohibited Uses)
We must avoid such situations.
Or, maybe you have special agreement with licensor?

**Comment by robertgarrigos** [comment]
I'm not so sure, so I asked them. Waiting for an answer. Thanks.

**Comment by robertgarrigos** [comment]
Got the answer. Deleted. Sorry about this.
